FROM php:laravel

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp

RUN curl -s https://raw.githubusercontent.com/composer/getcomposer.org/877cb10b101957ef8bbb9d196f711dbb8a011bb4/web/installer | php -- --install-dir=/bin --filename=composer --quiet

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN sed -i \
  -e "s@http://deb.debian.org@https://mirrors.huaweicloud.com@g" \
  -e "s@http://security.debian.org@https://mirrors.huaweicloud.com@g" \
  /etc/apt/sources.list

RUN apt-get update && apt-get install --no-install-recommends -y git unzip

WORKDIR /app

ENTRYPOINT ["/bin/sh", "/docker-entrypoint.sh"]

CMD ["composer"]

